# config.mk
#
# Product-specific compile-time definitions.
#

DEVICE_PATH := device/valve/jupiter

# The generic product target doesn't have any hardware-specific pieces.
TARGET_NO_BOOTLOADER := true
TARGET_CPU_ABI := x86_64
TARGET_ARCH := x86_64
TARGET_ARCH_VARIANT := x86_64

TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := x86_64

TARGET_USES_64_BIT_BINDER := true

TARGET_BOARD_PLATFORM := jupiter

# Kernel
BOARD_KERNEL_IMAGE_NAME := bzImage
TARGET_KERNEL_CONFIG := android_jupiter_defconfig
TARGET_KERNEL_SOURCE := kernel/valve/jupiter
TARGET_KERNEL_ADDITIONAL_FLAGS := \
    HOSTCFLAGS="-fuse-ld=lld -Wno-unused-command-line-argument"
TARGET_KERNEL_NO_GCC := false
TARGET_KERNEL_LLVM_BINUTILS := true
NEED_KERNEL_MODULE_RAMDISK := false

# Verity
BOARD_ENABLE_AVB := false

# Selinux
SELINUX_IGNORE_NEVERALLOWS := true
BOARD_SEPOLICY_DIRS += build/target/board/generic/sepolicy
BOARD_SEPOLICY_DIRS += build/target/board/generic_x86/sepolicy

# Some framework code requires this to enable BT
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/valve/jupiter/bluetooth

# Audio
BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
USE_XML_AUDIO_POLICY_CONF := 1

# Camera
USE_CAMERA_STUB := true

# Mesa
BOARD_MESA3D_USES_MESON_BUILD := true
BOARD_GPU_DRIVERS := radeonsi
BOARD_MESA3D_VULKAN_DRIVERS := amd
BOARD_MESA3D_GALLIUM_DRIVERS := radeonsi
BOARD_MESA3D_BUILD_LIBGBM := true
BOARD_USES_DRM_GRALLOC := false
BOARD_USES_DRM_HWCOMPOSER := true
BOARD_USES_MINIGBM := true
BOARD_USES_GRALLOC1 := true
TARGET_USES_HWC2 := true
TARGET_HARDWARE_3D := true
PRODUCT_REQUIRES_INSECURE_EXECMEM_FOR_SWIFTSHADER := true
USE_OPENGL_RENDERER := true

# HIDL
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/manifest.xml

# WLAN
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WPA_SUPPLICANT_VERSION := VER_2_1_DEVEL
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true

# PDK does not use ext4 image, but it is added here to prevent build break.
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 4294967296
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824
BOARD_CACHEIMAGE_PARTITION_SIZE := 69206016
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 512

TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true